# NumPy 랩업 문제
다음 문제들은 NumPy의 기본 개념부터 고급 개념까지 순차적으로 학습할 수 있도록 설계되었습니다. 

문제의 난이도는 하, 중, 상으로 나뉘어 있으며, 각각 5개의 문제로 구성되어 있습니다.



## 1단계 문제


1. 크기가 10인 null 벡터를 만드세요. (힌트: `np.zeros()`)


In [1]:
import numpy as np

In [6]:
np1 = np.zeros(10)
np1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. numpy 버전과 설정을 출력하세요. (힌트: `np.__version__`, `np.show_config()`)


In [9]:
np.__version__

'2.3.0'

In [10]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: C:/a/numpy/numpy/.openblas
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-ly2cw5el/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  US

3. 값이 10에서 49까지인 벡터를 만드세요. (힌트: `np.arange(10, 50)`)


In [15]:
np2 = np.arange(10, 50)
np2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. 벡터를 역순으로 만드세요 (첫 번째 요소가 마지막이 됩니다). (힌트: 배열을 뒤집기 위해 `[::-1]`)


In [16]:
np2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5. 크기가 3x3이고 0에서 8까지의 값을 갖는 행렬을 만드세요. (힌트: `np.arange()`와 `reshape()`)


In [18]:
np3 = np.arange(9).reshape(3,3)
np3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 2단계 문제


1. 1D 배열을 3x3 행렬로 변환하세요. (힌트: `reshape()`)


In [21]:
np4 = np.arange(9)
np4
np4.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2. 0에서 1 사이의 랜덤한 값으로 채워진 3x3 배열을 만드세요. (힌트: `np.random.random()`)


In [25]:
np.random.random(9).reshape(3,3)

array([[0.43781905, 0.37045807, 0.97300178],
       [0.63348776, 0.31544598, 0.69584826],
       [0.45916589, 0.40015229, 0.57882226]])

3. 5x5 단위 행렬을 만드세요. (힌트: `np.eye(5)`)


In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

4. 임의의 1D 배열에서 가장 큰 값의 인덱스를 찾으세요. (힌트: `np.argmax()`)


In [35]:
np5 = np.arange(5)
np.argmax(np5)

np.int64(4)

5. 크기가 10인 배열을 생성하고, 3에서 8까지의 값을 0으로 바꾸세요. (힌트: 슬라이싱과 배열 인덱싱)


In [31]:
np6 = np.arange(10)
np6[3:9] = 0
np6

array([0, 1, 2, 0, 0, 0, 0, 0, 0, 9])

## 3단계 문제


1. 임의의 배열에서 가장 작은 값과 가장 큰 값을 교환하세요. (힌트: `np.min()`, `np.max()`와 인덱싱)


In [43]:
np_3d = np.arange(18).reshape(2,3,3)
print(np_3d)
np.min(np_3d), np.max(np_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


(np.int64(0), np.int64(17))

2. 3차원 배열의 각 슬라이스마다 평균값을 계산하세요. (힌트: `np.mean()`과 축 설정)


In [45]:
np.mean(np_3d, axis = 2)

array([[ 1.,  4.,  7.],
       [10., 13., 16.]])

3. 크기가 100인 배열을 생성하고 평균, 표준편차를 계산하세요. (힌트: `np.mean()`, `np.std()`)


In [47]:
np7 = np.arange(100)
np.mean(np7), np.std(np7)

(np.float64(49.5), np.float64(28.86607004772212))

4. 주어진 2D 배열에서 고유한 행을 찾으세요. (힌트: `np.unique()`와 `axis` 설정)


In [57]:
np9 = np.array([[1,3,4,4,5], [2,4,3,7,6], [4,0,0,0,0], [4,0,0,0,0]])
np.unique(np9, axis = 0)

array([[1, 3, 4, 4, 5],
       [2, 4, 3, 7, 6],
       [4, 0, 0, 0, 0]])

5. 임의의 10x10 배열에서 가장 큰 값 5개를 찾으세요. (힌트: `np.argsort()`와 슬라이싱)


In [84]:
np10 = np.random.randint(1, 101, size=(10, 10))
print(np10)
np10_2 = np10.reshape(100)
np10_2[np.argsort(np10_2)[-5:]]

[[100  43  98  77  18  10  68   4  78  76]
 [ 25  80  90  22   2  45  36  46  41  83]
 [ 69  36  48  99  83  30  15  40  31  26]
 [ 30  67 100  61  46  82  97  47  67  76]
 [ 89   4  22  75  35  98  76  44   9  50]
 [ 49 100 100  22  74  73  19  85  30 100]
 [  6  11  42   7  19  73  17  70  82  52]
 [ 90  44  94   1   7  63  70  98  47  49]
 [ 73   6  40  33  29  34   6  27  82  99]
 [ 17  20   5  95  99  69  16  84  13  15]]


array([100, 100, 100, 100, 100], dtype=int32)